[project]
name = "harshp.com"
version = "3.0.0"
description = "Code generator for harshp.com"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "pygments>=2.19.2",
    "pyshacl>=0.30.1",
    "rdflib>=7.4.0",
    "rdflib-jsonld>=0.6.2",
]
